name: chat_ads
description: "Um aplicativo de um chat b√°sico."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.0.0
  firebase_core: ^3.0.0
  image_picker: ^1.0.4
  http: ^1.6.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  geolocator: ^14.0.2
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
